[package]
name = "grandpa-prover"
version = "0.1.0"
edition = "2021"
authors = ["Seun Lanlege <seunlanlege@gmail.com>"]

[build-dependencies]
anyhow = "1.0.66"
once_cell = "1.16.0"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
subxt-codegen = { package = "codegen", path = "../../../utils/subxt/codegen" }

[dependencies]
hex = "0.4.3"
anyhow = "1.0.64"
serde = "1.0.144"
subxt = { git = "https://github.com/paritytech/subxt", rev = "c0198acea854b24e161dbeb714e71d56830d51ef", features = ["substrate-compat"] }
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
derive_more = "0.99.17"
downcast-rs = "1.2.0"
jsonrpsee = { version = "0.16.2", features = ["async-client", "jsonrpsee-ws-client"] }
jsonrpsee-ws-client = "0.16.2"
finality-grandpa = "0.16.0"

finality-grandpa-rpc = { package = "sc-finality-grandpa-rpc", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-state-machine = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false }

beefy-prover = { path = "../../beefy/prover" }
primitives = { package = "grandpa-light-client-primitives", path = "../primitives" }
light-client-common = { path = "../../../light-clients/common" }
subxt-generated = { path = "../../../utils/subxt/generated" }

[features]
build-metadata-from-ws = []
