[workspace]
resolver = "2"
members = [
    # core ibc implementation
    "ibc/derive",
    "ibc/modules",
    "ibc/proto",
    "ibc/proto-compiler",

    # ibc contracts for different blockchain runtimes
    "contracts/pallet-ibc/ping",
    "contracts/pallet-ibc/primitives",
    "contracts/pallet-ibc/rpc",
    "contracts/pallet-ibc/runtime-api",
    "contracts/pallet-ibc",
    "contracts/pallet-ibc/simple-iavl",

    # algorithms
    "algorithms/beefy/verifier",
    "algorithms/beefy/prover",
    "algorithms/beefy/primitives",
    "algorithms/grandpa/verifier",
    "algorithms/grandpa/prover",
    "algorithms/grandpa/primitives",

    # ibc light clients
    "light-clients/common",
    "light-clients/ics07-tendermint",
    "light-clients/ics10-grandpa",
    "light-clients/ics11-beefy",
    "light-clients/ics13-near",

    # hyperspace
    "hyperspace",
    "hyperspace/core",
    "hyperspace/primitives",
    "hyperspace/parachain",
    "hyperspace/cosmos",
    "hyperspace/testsuite",
    "hyperspace/metrics",

    # utilities
    "utils/subxt/codegen",
    "utils/subxt/generated",
    "utils/parachain-node",
    "utils/parachain-node/runtime",
#     "utils/simnode"
]

[patch."https://github.com/paritytech/jsonrpsee"]
jsonrpsee = { version = "0.16.2" }

[patch.crates-io]
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-api-proc-macro = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-core-hashing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-debug-derive = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-externalities = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-panic-handler = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-runtime-interface-proc-macro = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-state-machine = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-storage = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-version-proc-macro = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-wasm-interface = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
sp-weights = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
try-runtime-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }

[patch."https://github.com/paritytech/substrate"]
sc-executor = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sc-executor-common = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sc-executor-wasmtime = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-api = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-api-proc-macro = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-application-crypto = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-arithmetic = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-core = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-core-hashing = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-debug-derive = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-externalities = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-io = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-keyring = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-keystore = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-panic-handler = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-runtime = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-runtime-interface = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-runtime-interface-proc-macro = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-state-machine = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-std = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-storage = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-tracing = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-trie = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-version = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-version-proc-macro = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-wasm-interface = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
sp-weights = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }
try-runtime-cli = { git = "https://github.com/paritytech//substrate.git", branch = "polkadot-v0.9.38" }

