[package]
name = "beefy-generic-client"
version = "0.1.0"
edition = "2021"
authors = ["Composable developers"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22" }
sp-runtime = { default-features = false,  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22" }
sp-core-hashing = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22" }

beefy-mmr = { package = "pallet-beefy-mmr", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22", default-features = false }
pallet-mmr = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22" }
pallet-mmr-primitives = { package = "sp-mmr-primitives", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22" }
beefy-primitives = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22" }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
rs_merkle = { version = "1.2.0", default-features = false }
mmr-lib= { package = "ckb-merkle-mountain-range", version = "0.3.2", default-features = false }
derive_more = { version = "0.99", default-features = false, features = ["from"]  }
# Mock deps
subxt = { version = "0.21.0", optional = true }
tokio = { version = "1.17.0", features = ["full"], optional = true }
hex-literal = { version = "0.3.4", optional = true }
serde_json = { version = "1.0.74", optional = true }
pallet-mmr-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22", optional = true }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22", optional = true}
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22", optional = true }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22", optional = true }

[dev-dependencies]
subxt = "0.21.0"
tokio = { version = "1.17.0", features = ["full"] }
hex-literal = "0.3.4"
serde_json = "1.0.74"
pallet-mmr-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.22" }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-std/std",
    "sp-runtime/std",
    "sp-core/std",
    "sp-core/std",
    "sp-io/std",
    "beefy-mmr/std",
    "beefy-primitives/std",
    "pallet-mmr/std",
    "pallet-mmr-primitives/std",
    "rs_merkle/std",
    "mmr-lib/std"
]
mocks = ["std", "subxt", "hex-literal", "serde_json", "pallet-mmr-rpc", "frame-support", "sp-io", "sp-trie"]
