[package]
name = "ibc-relayer"
version = "0.1.0"
edition = "2021"
authors = [""]

[[bin]]
name = "ibc-relayer"
path = "./bin/main.rs"

[dependencies]
futures = "0.3.21"
async-trait = "0.1.53"
tokio = { version = "1.19.2", features = ["macros"] }
ibc = { git = "https://github.com/composableFi/ibc-rs.git", branch = "master" }
