[package]
name = "hyperspace"
version = "0.1.0"
edition = "2021"
authors = ["Composable Developers"]

[[bin]]
name = "hyperspace"
path = "./bin/main.rs"

[dependencies]
primitives = { path = "primitives", package = "hyperspace-primitives" }
parachain = { path = "parachain", package = "hyperspace-parachain", optional = true }
cosmos = { path = "cosmos", package = "hyperspace-cosmos", optional = true }
near = { path = "near", package = "hyperspace-near", optional = true }

# crates.io
anyhow = "1.0.58"
futures = "0.3.21"
async-trait = "0.1.53"
log = "0.4.17"
env_logger = "0.9.0"
hex = "0.4.3"
tokio = { version = "1.19.2", features = ["macros", "sync"] }
codec = { version = "3.0.0", package = "parity-scale-codec" }

# ibc
ibc = { git = "https://github.com/composableFi/ibc-rs", rev = "9925f24c5061832ec5d5a0f4b16a1802dbb75128", features = ["ics11_beefy"] }
ibc-proto = { git = "https://github.com/composableFi/ibc-rs", rev = "9925f24c5061832ec5d5a0f4b16a1802dbb75128" }
tendermint-proto = { git = "https://github.com/composableFi/tendermint-rs", rev = "5a74e0f8da4d3dab83cc04b5f1363b018cf3d9e8" }

[features]
parachain = ["dep:parachain"]
near = ["dep:near"]
cosmos = ["dep:cosmos"]
testing = []

[workspace]
members = [
    "primitives",
    "parachain",
    "cosmos",
    "near",
    "testsuite",
]

#[[test]]
#name = "parachain_ibc_test"
#harness = false
#path = "tests/parachain/parachain_ibc_test.rs"
#
#[[test]]
#name = "parachain_token_transfer"
#harness = false
#path = "tests/parachain/parachain_token_transfer.rs"
#
#[[test]]
#name = "set_up_transfer_channel"
#harness = false
#path = "tests/parachain/set_up_transfer_channel.rs"
