[package]
name = "beefy-generic-client"
version = "0.1.0"
edition = "2021"
authors = ["Composable developers"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-core-hashing = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }

beefy-mmr = { package = "pallet-beefy-mmr", default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-mmr = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
pallet-mmr-primitives = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16" }
beefy-primitives = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.16"}
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
#scale-info = { version = "1.0", features = ["derive"] }

rs-merkle = { package = "rs_merkle", git = "https://github.com/ComposableFi/rs-merkle.git", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-std/std",
    "sp-runtime/std",
    "sp-core/std",
    "sp-core/std",
    "sp-io/std",
    "beefy-mmr/std",
    "beefy-primitives/std",
    "pallet-mmr/std",
    "pallet-mmr-primitives/std",
    "rs-merkle/std"
]