[package]
edition = "2021"
homepage = "https://composable.finance"
name = "pallet-ibc"
version = "0.0.1"
authors = ["Seun Lanlege <seunlanlege@gmail.com>", "David Salami <david.salami@gmail.com>"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[package.metadata.cargo-udeps.ignore]
normal = ["frame-benchmarking", "pallet-ibc-ping"]

[dependencies]
# crates.io
log = { version = "0.4.0", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.45", default-features = false }
sha2 = { version = "0.10.2", default-features = false }
derive_more = { version = "0.99.17", default-features = false, features = ["from", "display"]  }
# substrate
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27", default-features = false }
parachain-info = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "polkadot-v0.9.27" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27", default-features = false }
cumulus-primitives-core  = { default-features = false, git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.27" }
# ibc
ibc-proto = { path = "../../ibc/proto", default-features = false }
tendermint = { git = "https://github.com/composableFi/tendermint-rs", rev = "5a74e0f8da4d3dab83cc04b5f1363b018cf3d9e8", optional = true, default-features = false }
tendermint-proto = { git = "https://github.com/composableFi/tendermint-rs", rev = "5a74e0f8da4d3dab83cc04b5f1363b018cf3d9e8", default-features = false }
ics23 = { git = "https://github.com/composablefi/ics23", rev = "b500a5c6068eb53c83c4c6c13bd9d8c25e0bf927", default-features = false }
grandpa-client-primitives = { package = "grandpa-light-client-primitives", path = "../../algorithms/grandpa/primitives", default-features = false }
beefy-client-primitives = { package = "beefy-light-client-primitives", path = "../../algorithms/beefy/primitives", default-features = false }
light-client-common = { path = "../../light-clients/common", default-features = false }
ics10-grandpa = { path = "../../light-clients/ics10-grandpa", default-features = false }
ics11-beefy = { path = "../../light-clients/ics11-beefy", default-features = false }
ics07-tendermint = { path = "../../light-clients/ics07-tendermint", default-features = false }

# local deps
ibc-primitives = { path = "primitives", default-features = false }

# optional
hex = { version = "0.4.3", default-features = false, optional = true }
hex-literal = { version = "0.3.4", default-features = false, optional = true }
prost = { version = "0.10", default-features = false, optional = true }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27", default-features = false, optional = true }
pallet-ibc-ping = { path = "ping", default-features = false, optional = true }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27", default-features = false, optional = true }
simple-iavl = { git = "https://github.com/ComposableFi/simple-avl", rev = "452a1126bfb8a861354b413755ac3c8fda3da4ec", default-features = false, optional = true }

[dependencies.ibc]
path = "../../ibc/modules"
default-features = false

[dependencies.ibc-derive]
path = "../../ibc/derive"
default-features = false

[dependencies.codec]
package = "parity-scale-codec"
version = "3.0.0"
features = ["derive"]
default-features = false

[dependencies.tendermint-light-client-verifier]
git = "https://github.com/composableFi/tendermint-rs"
rev = "5a74e0f8da4d3dab83cc04b5f1363b018cf3d9e8"
default-features = false

[dev-dependencies]
chrono = "0.4.19"
hex = "0.4.3"
hex-literal = { version = "0.3.4" }
orml-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "377213f750755cc48e80a3131eaae63b5eda8362" }
orml-traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "377213f750755cc48e80a3131eaae63b5eda8362" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
prost = { version = "0.10" }
serde = { version = "1.0" }
simple-iavl = { git = "https://github.com/ComposableFi/simple-avl", rev = "452a1126bfb8a861354b413755ac3c8fda3da4ec" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
tendermint = { git = "https://github.com/composableFi/tendermint-rs", rev = "5a74e0f8da4d3dab83cc04b5f1363b018cf3d9e8" }
balances = { package = "pallet-balances", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27", default-features = false }
pallet-assets = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
pallet-ibc-ping = { path = "ping", default-features = false }

[dev-dependencies.ibc]
path = "../../ibc/modules"
features = ["mocks"]

[features]
default = ["std"]
std = [
  "codec/std",
  "log/std",
  "scale-info/std",
  "serde_json/std",
  "sha2/std",
  "frame-benchmarking/std",
  "frame-support/std",
  "frame-system/std",
  "sp-runtime/std",
  "sp-core/std",
  "sp-std/std",
  "sp-io/std",
  "sp-trie/std",
  "cumulus-primitives-core/std",
  "pallet-assets/std",
  "ibc/std",
  "ibc-proto/std",
  "ibc-primitives/std",
  "parachain-info/std",
  "grandpa-client-primitives/std",
  "beefy-client-primitives/std",
  "light-client-common/std",
  "ics10-grandpa/std",
  "ics11-beefy/std",
  "ics07-tendermint/std",
]

runtime-benchmarks = [
  "frame-benchmarking",
  "pallet-ibc-ping",
  "frame-system/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "tendermint",
  "hex-literal",
  "pallet-timestamp",
  "pallet-timestamp/runtime-benchmarks",
  "hex",
  "simple-iavl",
  "prost",
  "ibc-primitives/runtime-benchmarks",
]

try-runtime = ["frame-support/try-runtime"]
