[package]
name = "codegen"
version = "0.1.0"
edition = "2021"
authors = ["Seun Lanlege <seunlanlege@gmail.com>"]

[[bin]]
name = "codegen"
path = "bin/main.rs"

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
anyhow = "1.0.66"
clap = { version = "3.2.22", features = ["derive", "env"] }
serde_json = "1.0.91"

subxt-codegen = { git = "https://github.com/ComposableFi/subxt", rev = "7a54d51ffe1d2daf785d13040276e5cbe30c29ed" }
jsonrpsee = { version = "0.15.1", features = ["async-client", "client-ws-transport", "http-client"] }
frame-metadata = { version = "15.0.0", features = ["v14", "std"] }
syn = "1.0.98"
codec = { package = "parity-scale-codec", version = "3.0.0" }
hex = "0.4.3"
wasm-testbed = { git = "https://github.com/composableFi/subwasm", rev = "f0f06c05179bd318a03663808b7d1aee6e5875b6" }
