name: Cargo Check

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master


jobs:
  checker:
    strategy:
      matrix:
        os: [ubuntu-latest]
    concurrency:
      group: lint-${{ github.ref }}
      cancel-in-progress: true
    container:
      image: paritytech/ci-linux:production
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Rustup show
      run: |
        rustup show

    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'

    - name: check workspace
      run: cargo check --workspace --locked

    - name: check no_std
      run: ./scripts/no_std_checks.sh

    - name: pallet-ibc check benchmarks
      run: cargo test -p pallet-ibc --release --locked --features=runtime-benchmarks