name: "Build and publish Hyperspace Docker image"

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  
  build-and-publish:

    name: Build & push docker image
    
    runs-on:
      - self-hosted
      - x64-monster
    
    concurrency:
      group: hyperspace-docker-image-${{ github.ref }}
      cancel-in-progress: true
    
    strategy:
      fail-fast: true

    steps:
    - name: Clean up
      continue-on-error: true
      run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE
        docker system prune --force --all --volumes

    - name: Install dependencies
      run: |
        sudo apt-get install -y make build-essential

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=ref,event=branch
          type=sha,prefix={{branch}}-

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        file: scripts/hyperspace.Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
