name: "Build and publish Hyperspace Docker image"

on:
  push:
    branches:
      - master
      - vmarkushin/cosmos-skip-client-updates

jobs:
  build-and-publish:
    runs-on:
      - self-hosted
      - x64-monster
    concurrency:
      group: hyperspace-docker-image-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: true

    steps:
    - name: Clean up
      continue-on-error: true
      run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE
        docker system prune --force --all --volumes

    - name: Install dependencies
      run: |
        sudo apt-get install -y make build-essential

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image
      run: make -f hyperspace/Makefile build-docker-image-hyperspace

    - name:  Docker push
      run: make -f hyperspace/Makefile publish-docker-image-hyperspace
