# This workflow pushes new parachain-node docker images on every new push on master.
#
# All the images above have support for linux/amd64 and linux/arm64.
#
# Due to QEMU virtualization used to build multi-platform docker images

name: "Build and publish Parachain-node Docker image"

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on:
      - self-hosted
      - x64-monster
    concurrency:
      group: parachain-node-docker-image-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: true

    steps:
    - name: Clean up
      continue-on-error: true
      run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE
        docker system prune --force --all --volumes

    - name: Install dependencies
      run: |
        sudo apt-get install -y make build-essential

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - 
      name: Create Docker Image Tag
      run:  |
        SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)
        echo "DOCKER_IMAGE_TAG=${SHORT_SHA}-$(date +%s)" >> $GITHUB_ENV
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - 
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: scripts/parachain.Dockerfile
        context: .
        push: true
        platforms: linux/amd64
        tags: |
          composablefi/parachain-node:${{ env.DOCKER_IMAGE_TAG }}
