name: Test

on:
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    name: Composable Test
    #container:
    #  image: composablefi/composable-sandbox:latest
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2

    #- name: Run Test
    #  run: |
    #    cargo test