name: Test

on:
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    name: Composable Test
    runs-on: [ubuntu-latest]
    container:
      image: composablefi/ci-linux:2022-04-18
    steps:
    - uses: actions/checkout@v2

    - name: Download a Composable collator
      run: |
        cd scripts/polkadot-launch
        mkdir -p composable/target/release
        cd composable
        curl https://github.com/ComposableFi/composable/releases/download/v2.2.1/composable -Lo ./target/release/composable
        chmod +x target/release/composable
        target/release/composable --version

    - name: Build a Polkadot relay chain
      run: |
        cd scripts/polkadot-launch
        git clone -b mmr-polkadot-v0.9.22 https://github.com/composableFi/polkadot
        cd polkadot
        cargo build --release
        ./target/release/polkadot --version

    - name: Run polkadot-launch
      timeout-minutes: 5
      env:
        DEBIAN_FRONTEND: noninteractive
        LOG_FILE: /tmp/polka-launch/polka-launch.log
      run: |
        cd scripts/polkadot-launch
        mkdir -p /tmp/polka-launch
        curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
        apt update -y
        apt install -y --no-install-recommends nodejs
        npm install --global yarn

        yarn
        yarn composable > "${LOG_FILE}" 2>&1 &
        # yarn composable

        # wait for polka-launch
        echo "wait for polka-launch"
        while true; do
          sleep 1
          echo "====="
          echo "====="
          echo "====="
          cat "${LOG_FILE}"
          stdout=$(tail -n 1 "${LOG_FILE}" | grep "POLKADOT LAUNCH COMPLETE")
          if [ -z "$stdout" ]; then
            true
          else
            break
          fi
        done
        echo "wait for polka-launch"

#        while IFS="" read -r string; do
#          echo $string
#          matched_string=$(echo "$string" | grep "POLKADOT LAUNCH COMPLETE")
#          if [ -z "${matched_string}" ]; then
#            true
#          else
#            break
#          fi
#        done < <(tail -f "${LOG_FILE}")

    - name: Run Test
      env:
        NODE_ENDPOINT: "ws://composable:9944"
      run: |
        cargo test
