name: Test

on:
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    name: Composable Test
    #container:
    #  image: composablefi/composable-sandbox:latest
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Download Docker-CompooseFile
      run: wget https://github.com/ComposableFi/composable/blob/main/integration-tests/runtime-tests/docker-compose.yml
    
    - name: Build the stack
      run: docker-compose up -d
    
    #- name: Run Test
    #  uses: docker://composablefi/composable-sandbox
      #with: 
      # args: cargo test